-- Wizzokraft Psychometric Test — day-wise survey (replaces the 60-question scored test)
-- Run this in the Supabase SQL Editor, then run content/survey-seed.sql
-- (generated by `node scripts/parse-survey.mjs`).
--
-- admin_config (the admin password, from the old test's functions.sql) is reused;
-- it must already exist.
--
-- Security model: every survey table is RLS-locked with no policies. The browser
-- only goes through the SECURITY DEFINER functions below.

-- ---------- Tables ----------

-- Same 30 questions each day, asked in a different order.
--   position    = order shown on that day (1..30)
--   question_no = the question's number in DAY 1 (stable across days)
create table if not exists survey_questions (
  day         int  not null check (day between 1 and 3),
  position    int  not null check (position between 1 and 30),
  question_no int  not null check (question_no between 1 and 30),
  text        text not null,
  primary key (day, position),
  unique (day, question_no)
);

-- Single row: which day is currently open (null = test closed).
create table if not exists survey_settings (
  id         int primary key default 1,
  active_day int check (active_day between 1 and 3),
  constraint survey_settings_single_row check (id = 1)
);
insert into survey_settings (id, active_day) values (1, null) on conflict (id) do nothing;

create table if not exists survey_submissions (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  day         int  not null check (day between 1 and 3),
  name        text not null,
  dob         date not null,
  designation text,
  department  text,
  -- [{ question_no, position, text, value (5..1), label }], ordered by question_no
  answers     jsonb not null
);
-- One submission per person per day. There is no employee number, so a person
-- is identified by name (case/space-insensitive) + date of birth.
create or replace function survey_person_key(p_name text)
returns text
language sql
immutable
as $$ select lower(regexp_replace(trim(p_name), '\s+', ' ', 'g')) $$;

create unique index if not exists survey_submissions_person_day
  on survey_submissions (survey_person_key(name), dob, day);

alter table survey_questions   enable row level security;
alter table survey_settings    enable row level security;
alter table survey_submissions enable row level security;

-- ---------- Answer scale ----------

create or replace function survey_label(p_value int)
returns text
language sql
immutable
as $$
  select case p_value
    when 5 then 'Highly Agree'
    when 4 then 'Slightly Agree'
    when 3 then 'Neutral'
    when 2 then 'Disagree'
    when 1 then 'Highly Disagree'
  end;
$$;

-- ---------- Public functions ----------

-- get_survey: the open day and its questions in that day's order.
-- Returns { day: null, questions: [] } when the test is closed.
create or replace function get_survey()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'day', s.active_day,
    'questions', coalesce((
      select jsonb_agg(jsonb_build_object('position', q.position, 'question_no', q.question_no, 'text', q.text)
                       order by q.position)
      from survey_questions q where q.day = s.active_day
    ), '[]'::jsonb)
  )
  from survey_settings s where s.id = 1;
$$;
grant execute on function get_survey() to anon, authenticated;

-- has_submitted_survey: has this person (name + DOB) already submitted for the open day?
create or replace function has_submitted_survey(p_name text, p_dob date)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from survey_submissions x, survey_settings s
    where s.id = 1 and x.day = s.active_day
      and survey_person_key(x.name) = survey_person_key(p_name) and x.dob = p_dob
  );
$$;
grant execute on function has_submitted_survey(text, date) to anon, authenticated;

-- submit_survey
--   p_person  : { name, dob, designation, department }
--   p_answers : [ { "question_no": 1, "value": 5 }, ... ]  (all 30, value 1..5)
-- The day is taken from survey_settings, never from the browser.
create or replace function submit_survey(p_person jsonb, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_day     int;
  v_name    text := nullif(regexp_replace(trim(p_person->>'name'), '\s+', ' ', 'g'), '');
  v_dob     date := nullif(p_person->>'dob', '')::date;
  v_total   int;
  v_answers jsonb;
  v_id      uuid;
begin
  select active_day into v_day from survey_settings where id = 1;
  if v_day is null then
    raise exception 'survey_closed';
  end if;
  if v_name is null or v_dob is null then
    raise exception 'name and dob are required';
  end if;
  if exists (select 1 from survey_submissions
             where day = v_day and survey_person_key(name) = survey_person_key(v_name) and dob = v_dob) then
    raise exception 'already_submitted';
  end if;

  select count(*) into v_total from survey_questions where day = v_day;

  -- Join answers to the day's questions; only valid, distinct answers survive.
  select coalesce(jsonb_agg(jsonb_build_object(
           'question_no', q.question_no,
           'position', q.position,
           'text', q.text,
           'value', a.value,
           'label', survey_label(a.value)
         ) order by q.question_no), '[]'::jsonb)
    into v_answers
    from (
      select distinct on ((e->>'question_no')::int)
             (e->>'question_no')::int as question_no, (e->>'value')::int as value
      from jsonb_array_elements(p_answers) e
    ) a
    join survey_questions q on q.day = v_day and q.question_no = a.question_no
    where a.value between 1 and 5;

  if jsonb_array_length(v_answers) <> v_total then
    raise exception 'incomplete_answers: got %, expected %', jsonb_array_length(v_answers), v_total;
  end if;

  insert into survey_submissions (day, name, dob, designation, department, answers)
  values (
    v_day, v_name, v_dob,
    nullif(trim(p_person->>'designation'), ''),
    nullif(trim(p_person->>'department'), ''),
    v_answers
  )
  returning id into v_id;

  return jsonb_build_object('id', v_id, 'day', v_day);
end;
$$;
grant execute on function submit_survey(jsonb, jsonb) to anon, authenticated;

-- ---------- Admin functions (password in admin_config) ----------

create or replace function survey_check_password(p_password text)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not coalesce((select password = p_password from admin_config where id = 1), false) then
    raise exception 'unauthorized';
  end if;
end;
$$;
revoke execute on function survey_check_password(text) from public, anon, authenticated;

-- get_survey_admin_data: open day, all submissions, and the questions (DAY 1 numbering).
create or replace function get_survey_admin_data(p_password text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  perform survey_check_password(p_password);
  return jsonb_build_object(
    'active_day', (select active_day from survey_settings where id = 1),
    'questions', coalesce((
      select jsonb_agg(jsonb_build_object('question_no', question_no, 'text', text) order by question_no)
      from survey_questions where day = 1
    ), '[]'::jsonb),
    'submissions', coalesce((
      select jsonb_agg(to_jsonb(s) order by s.created_at desc) from survey_submissions s
    ), '[]'::jsonb)
  );
end;
$$;
grant execute on function get_survey_admin_data(text) to anon, authenticated;

-- set_active_day: open Day 1/2/3, or pass null to close the test.
create or replace function set_active_day(p_password text, p_day int)
returns int
language plpgsql
security definer
set search_path = public
as $$
begin
  perform survey_check_password(p_password);
  if p_day is not null and p_day not between 1 and 3 then
    raise exception 'invalid day: %', p_day;
  end if;
  update survey_settings set active_day = p_day where id = 1;
  return p_day;
end;
$$;
grant execute on function set_active_day(text, int) to anon, authenticated;
