// Parses DAY 1/2/3.docx (30 questions each, same questions in a different
// order per day) into a seed SQL file for the survey_questions table.
//
// question_no = the question's position in DAY 1, so answers can be compared
// across days even though each day asks them in a different order.
//
// Run: node scripts/parse-survey.mjs
// Output: content/survey-seed.sql (gitignored) — paste into the Supabase SQL Editor.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import mammoth from 'mammoth'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const OUT = path.join(ROOT, 'content')
const DAYS = [1, 2, 3]
const EXPECTED = 30

async function readDay(day) {
  const { value } = await mammoth.extractRawText({ path: path.join(ROOT, `DAY ${day}.docx`) })
  return value
    .split('\n')
    .map((l) => l.replace(/\s+/g, ' ').trim())
    .filter((l) => l && !/^DAY\s*\d+$/i.test(l))
}

// Compare questions loosely (dash variants / case / spacing) so tiny typing
// differences between the docs don't break the cross-day mapping.
const norm = (s) => s.toLowerCase().replace(/[‐-―−-]/g, '-').replace(/\s+/g, ' ').trim()
const sql = (s) => `'${s.replace(/'/g, "''")}'`

async function main() {
  const days = {}
  for (const d of DAYS) days[d] = await readDay(d)

  const errors = []
  for (const d of DAYS) {
    if (days[d].length !== EXPECTED) errors.push(`DAY ${d}: expected ${EXPECTED} questions, got ${days[d].length}`)
  }

  const canonical = new Map(days[1].map((q, i) => [norm(q), i + 1]))
  if (canonical.size !== days[1].length) errors.push('DAY 1 contains duplicate questions')

  const rows = []
  for (const d of DAYS) {
    const seen = new Set()
    days[d].forEach((text, i) => {
      const no = canonical.get(norm(text))
      if (!no) errors.push(`DAY ${d} Q${i + 1} not found in DAY 1: "${text}"`)
      else if (seen.has(no)) errors.push(`DAY ${d} repeats DAY 1 question ${no}`)
      else { seen.add(no); rows.push({ day: d, position: i + 1, question_no: no, text }) }
    })
  }

  if (errors.length) {
    console.error('Validation failed:')
    errors.forEach((e) => console.error('  - ' + e))
    process.exit(1)
  }

  const values = rows.map((r) => `  (${r.day}, ${r.position}, ${r.question_no}, ${sql(r.text)})`).join(',\n')
  const out = `-- Generated by scripts/parse-survey.mjs — do not edit by hand.
-- Re-runnable: replaces all survey questions.
delete from survey_questions;
insert into survey_questions (day, position, question_no, text) values
${values};
`
  fs.mkdirSync(OUT, { recursive: true })
  fs.writeFileSync(path.join(OUT, 'survey-seed.sql'), out)
  console.log(`OK: ${rows.length} rows (${DAYS.length} days x ${EXPECTED}) -> content/survey-seed.sql`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
